---
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  skip:
    - pip-compile
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-2020>=1.6.1
          - flake8-docstrings>=1.6.0
          - flake8-pytest-style>=1.6.0
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        # args: [--strict]
  - repo: https://github.com/pycqa/pylint
    rev: v3.0.3
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        entry: pip-compile --resolver=backtracking -q --no-annotate --output-file=requirements.txt pyproject.toml --extra test --strip-extras
        language: python
        files: ^(requirements\.txt|pyproject\.toml)$
        alias: deps
        language_version: "3.9" # minimal we support officially
        additional_dependencies:
          - pip>=22.3.1
      - id: pip-compile
        entry: pip-compile --resolver=backtracking -q --no-annotate --output-file=requirements.txt pyproject.toml --extra test --strip-extras --upgrade
        language: python
        files: ^(requirements\.txt|pyproject\.toml)$
        alias: up
        stages: [manual]
        language_version: "3.9" # minimal we support officially
        additional_dependencies:
          - pip>=22.3.1
