# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

boxes = ['alpine315', 'alpine37']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  boxes.each do |box|
    config.vm.define box do |conf|
      conf.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")
      conf.vm.hostname = box
      conf.vm.box = "generic/#{box}"
    end
  end
end
