# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

boxes = ['alpine315', 'alpine37']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  boxes.each do |box|
    config.vm.define box do |conf|
      conf.vm.box = box
      conf.vm.box_url = box
    end
  end
end
