# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  (1..2).each do |i|
    config.vm.define "multialpine0#{i}" do |webserver|
      webserver.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")
      webserver.vm.box = "generic/alpine315"
      webserver.vm.hostname = "multialpine0#{i}"
    end
  end
end
